### ISSUE TITLE
[phpng] Crash when query string has nested array keys

### ISSUE THREAD

**Issue by bmadzar** [m6w6/ext-http#11]
In testing the PHP 7 branch I've run into a strange issue:
When the query string contains nested array keys of the form `?a[0][0]=x&a[1][0]=x` (outer key changes), PHP crashes (SIGSEGV). 
It only happens with some scripts and not others; where it does happen, it happens reliably. I cannot figure out what the common factor is.

Backtrace:
```
#0  0x00000000007854b1 in _zend_hash_index_update ()
#1  0x00007f18351877c7 in push_param () from /php7/lib/php/extensions/no-debug-non-zts-20141001/http.so
#2  0x00007f1835186738 in php_http_params_parse () from /php7/lib/php/extensions/no-debug-non-zts-20141001/http.so
#3  0x00007f183518a81e in php_http_querystring_parse () from /php7/lib/php/extensions/no-debug-non-zts-20141001/http.so
#4  0x00007f183518a9ff in php_http_querystring_update () from /php7/lib/php/extensions/no-debug-non-zts-20141001/http.so
#5  0x00007f183518adae in zim_HttpQueryString___construct () from /php7/lib/php/extensions/no-debug-non-zts-20141001/http.so
#6  0x00000000007cc060 in ZEND_DO_FCALL_SPEC_HANDLER ()
#7  0x00000000007b68c8 in execute_ex ()
#8  0x00000000007b6d2e in zend_execute ()
#9  0x00000000007757a6 in zend_execute_scripts ()
#10 0x000000000070d56f in php_execute_script ()
#11 0x0000000000814de2 in main ()
```

Using latest source (GitHub) version of ext-http and PHP 7. Debian x86_64, clang 3.5.2.

**Comment by bmadzar** [comment]
I should mention: this does not happen with PHP 5.6.12 and ext-http 2.5.1.
