### ISSUE TITLE
[2.6.0] build failure with libevent 1.4

### ISSUE THREAD

**Issue by remicollet** [m6w6/ext-http#69]
On RHEL 6, using php 5.6, libevent 1.4.13

Trying to update for centos-scl repository (see https://blog.remirepo.net/post/2017/02/23/Additional-PHP-packages-for-RHSCL) from 2.5.6 (build was OK) to 2.6.0

```
/builddir/build/BUILD/sclo-php56-php-pecl-http-2.6.0/NTS/src/php_http_client_curl_event.c: In function 'php_http_client_curl_event_wait':
/builddir/build/BUILD/sclo-php56-php-pecl-http-2.6.0/NTS/src/php_http_client_curl_event.c:222: error: expected expression before 'do'
make: *** [src/php_http_client_curl_event.lo] Error 1
```

**Comment by remicollet** [comment]
Just try a quick fix:
```
--- src/php_http_client_curl_event.c	2017-04-10 15:26:27.462744647 +0200
+++ /tmp/php_http_client_curl_event.c	2017-04-10 15:25:56.673592781 +0200
@@ -19,10 +19,10 @@
 #	if !PHP_HTTP_HAVE_EVENT2 && /* just be really sure */ !(LIBEVENT_VERSION_NUMBER >= 0x02000000)
 #		include <event.h>
 #		define event_base_new event_init
-#		define event_assign(e, b, s, a, cb, d) do {\
-			event_set(e, s, a, cb, d); \
-			event_base_set(b, e); \
-		} while(0)
+static inline int event_assign(struct event *e, struct event_base *b, int s, short a, void (*cb)(int, short, void *), void *d) {
+	event_set(e, s, a, cb, d);
+	return event_base_set(b, e);
+}
 #	else
 #		if PHP_HTTP_HAVE_EVENT2
 #			include <event2/event.h>
```

Build run fine, but lot of failures:
```
TEST 2/192 [tests/bug66388.phpt]
========DIFF========
002+ exception 'http\Exception\RuntimeException' with message 'http\Client::send(): Failure when receiving data from the peer;  (http://localhost:9230/)' in /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug66388.php:20
003+ Stack trace:
004+ #0 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug66388.php(20): http\Client->send()
005+ #1 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(124): {closure}('9230', Resource id #5, Resource id #6, Resource id #7)
006+ #2 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(73): proc('/usr/bin/php', Array, Object(Closure))
007+ #3 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug66388.php(21): server('proxy.inc', Object(Closure))
008+ #4 {main}
009+ 
002- 200
========DONE========
FAIL Bug #66388 (Crash on POST with Content-Length:0 and untouched body) [tests/bug66388.phpt] 
TEST 7/192 [tests/bug69313.phpt]
========DIFF========
002+ exception 'http\Exception\RuntimeException' with message 'http\Client::send(): Failure when receiving data from the peer;  (http://localhost:8698/)' in /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug69313.php:14
003+ Stack trace:
004+ #0 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug69313.php(14): http\Client->send()
005+ #1 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(124): {closure}('8698', Resource id #6, Resource id #7, Resource id #8)
006+ #2 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(73): proc('/usr/bin/php', Array, Object(Closure))
007+ #3 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug69313.php(16): server('proxy.inc', Object(Closure))
008+ #4 {main}
002- HTTP/1.1 200 OK
003- Accept-Ranges: bytes
004- Content-Length: %d
005- Etag: "%s"
006- X-Original-Transfer-Encoding: chunked
008- GET / HTTP/1.1
010+ Done
009- Accept: */*
010- Content-Length: 3
011- Content-Type: text/plain
012- Host: localhost:%d
013- User-Agent: %s
014- X-Original-Content-Length: 3
015- 
016- foo
017- Done
========DONE========
FAIL Bug #69313 (http\Client doesn't send GET body) [tests/bug69313.phpt] 
TEST 8/192 [tests/bug69357.phpt]
========DIFF========
002+ exception 'http\Exception\RuntimeException' with message 'http\Client::send(): Failure when receiving data from the peer;  (http://localhost:8102/)' in /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug69357.php:12
003+ Stack trace:
004+ #0 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug69357.php(12): http\Client->send()
005+ #1 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(124): {closure}('8102', Resource id #5, Resource id #6, Resource id #7)
006+ #2 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(73): proc('/usr/bin/php', Array, Object(Closure))
007+ #3 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/bug69357.php(16): server('upload.inc', Object(Closure))
008+ #4 {main}
002- string(15) "HTTP/1.1 200 OK"
003- array(4) {
004-   ["Accept-Ranges"]=>
005-   string(5) "bytes"
006-   ["Etag"]=>
007-   string(10) ""%x""
008-   ["X-Original-Transfer-Encoding"]=>
009-   string(7) "chunked"
010-   ["Content-Length"]=>
011-   int(%d)
012- }
========DONE========
FAIL Bug #69357 (HTTP/1.1 100 Continue overriding subsequent 200 response code with PUT request) [tests/bug69357.phpt] 
TEST 12/192 [tests/client002.phpt]
========DIFF========
002+ PPPPPPPPPPexception 'http\Exception\RuntimeException' with message 'http\Client::send(): Failure when receiving data from the peer;  (http://localhost:9177/)' in /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/client002.php:22
003+ Stack trace:
004+ #0 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/client002.php(22): http\Client->send()
005+ #1 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(124): {closure}('9177', Resource id #5, Resource id #6, Resource id #7)
006+ #2 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/helper/server.inc(73): proc('/usr/bin/php', Array, Object(Closure))
007+ #3 /builddir/build/BUILD/php-pecl-http-2.6.0/NTS/tests/client002.php(24): server('proxy.inc', Object(Closure))
008+ #4 {main}
009+ 
002- P+
========DONE========
FAIL client observer [tests/client002.phpt] 
...
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Bug #66388 (Crash on POST with Content-Length:0 and untouched body) [tests/bug66388.phpt]
Bug #69313 (http\Client doesn't send GET body) [tests/bug69313.phpt]
Bug #69357 (HTTP/1.1 100 Continue overriding subsequent 200 response code with PUT request) [tests/bug69357.phpt]
client observer [tests/client002.phpt]
client once & wait [tests/client003.phpt]
client reset [tests/client004.phpt]
client response callback [tests/client005.phpt]
client response callback + dequeue [tests/client006.phpt]
client response callback + requeue [tests/client007.phpt]
client features [tests/client008.phpt]
client ssl [tests/client012.phpt]
client observers [tests/client013.phpt]
http client event base [tests/client015.phpt]
client once & wait with events [tests/client016.phpt]
client pipelining [tests/client018.phpt]
client proxy - don't send proxy headers for a standard request [tests/client020.phpt]
client cookies [tests/client021.phpt]
client seek [tests/client025.phpt]
client stream 128M [tests/client026.phpt]
client cookie woes [tests/client027.phpt]
client curl user handler [tests/client028.phpt]
client eventloop recursion [tests/client030.phpt]
client response transfer info [tests/clientresponse003.phpt]
=====================================================================
```

Perhaps you will see a possible mistake in my patch, and ar possible quick fix.
Else... perhaps no worth to support this old libevent version (as nobody have report about it)

**Comment by remicollet** [comment]
Stupid of me... RHEL also have libevent2 (v2.0.21), so problem solved.

BTW keep open if someone try to build against libevent 1.4
But you can probably close it.
